### ISSUE TITLE
%{key} is empty in PE 2015.2

### ISSUE THREAD

**Issue by dirtdiver9** [crayfishx/hiera-mysql#14] opened 2015-11-17 18:48 UTC
I am currently trying to upgrade to 2015.2 of PE and am running into a problem getting data out of the mysql backend that works fine on 3.8.

When I run the puppet master in foreground and debug I see that it queries the DB with an empty %{key} value.  %{hostname} and %{environment} work fine but key is empty.

Hiera on the command line works fine.

foreground run of puppet master run with agent:

...
Debug: hiera(): Hiera YAML backend starting
Debug: hiera(): Looking up ml_role in YAML backend
Debug: hiera(): Looking for data source env01
Debug: hiera(): Looking for data source common
Debug: hiera(): Looking for data source common_password
Debug: hiera(): Cannot find datafile /etc/puppetlabs/code/hieradata/master/common_password.yaml, skipping
Debug: hiera(): Looking for data source defaults
Debug: hiera(): [eyaml_backend]: Hiera eYAML backend starting
Debug: hiera(): Using Hiera 1.x backend API to access instance of class Hiera::Backend::Eyaml_backend. Lookup recursion will not be detected
Debug: hiera(): [eyaml_backend]: Set option: datadir = /etc/puppetlabs/code/hieradata/master
Debug: hiera(): [eyaml_backend]: Set option: pkcs7_private_key = /etc/puppetlabs/code/keyrings/private_key.pkcs7.pem
Debug: hiera(): [eyaml_backend]: Set option: pkcs7_public_key = /etc/puppetlabs/code/keyrings/public_key.pkcs7.pem
Debug: hiera(): [eyaml_backend]: Looking up ml_role in eYAML backend
Debug: hiera(): [eyaml_backend]: Looking for data source env01
Debug: hiera(): Cannot find datafile /etc/puppetlabs/code/hieradata/master/env01.eyaml, skipping
Debug: hiera(): [eyaml_backend]: Looking for data source common
Debug: hiera(): Cannot find datafile /etc/puppetlabs/code/hieradata/master/common.eyaml, skipping
Debug: hiera(): [eyaml_backend]: Looking for data source common_password
Debug: hiera(): [eyaml_backend]: Looking for data source defaults
Debug: hiera(): Cannot find datafile /etc/puppetlabs/code/hieradata/master/defaults.eyaml, skipping
Debug: hiera(): mysql_backend initialized
Debug: hiera(): JDBC mode false
Debug: hiera(): Using Hiera 1.x backend API to access instance of class Hiera::Backend::Mysql_backend. Lookup recursion will not be detected
Debug: hiera(): mysql_backend invoked lookup
Debug: hiera(): resolution type is priority
Debug: hiera(): Executing SQL Query: SELECT Value FROM ConfigValue WHERE ConfigKey = '' AND HostName = 'krkenv01lnxweb1' AND EnvironmentCode = 'env01' AND AppVersion is NULL
Debug: hiera(): Mysql Query returned 0 rows
Debug: hiera(): Executing SQL Query: SELECT Value FROM ConfigValue WHERE ConfigKey = '' AND HostName = 'krkenv01lnxweb1' AND EnvironmentCode = 'env01'
Debug: hiera(): Mysql Query returned 0 rows
Debug: hiera(): Executing SQL Query: SELECT Value FROM ConfigValue WHERE ConfigKey = '' AND HostName = 'krkenv01lnxweb1' AND EnvironmentCode  is NULL
Debug: hiera(): Mysql Query returned 0 rows
Debug: hiera(): Executing SQL Query: SELECT Value FROM ConfigValue WHERE ConfigKey = '' AND HostName is NULL AND EnvironmentCode = 'env01'
Debug: hiera(): Mysql Query returned 0 rows
Debug: hiera(): Executing SQL Query: SELECT Value FROM ConfigValue WHERE ConfigKey = '' AND DomainName = 'sky.dom' AND EnvironmentCode is NULL
Debug: hiera(): Mysql Query returned 0 rows
Debug: hiera(): Executing SQL Query: SELECT Value FROM ConfigValue WHERE ConfigKey = '' AND EnvironmentCode is NULL
Debug: hiera(): Mysql Query returned 0 rows
Debug: hiera(): Executing SQL Query: SELECT FactValue FROM Host WHERE FactName = '' AND HostName = 'krkenv01lnxweb1'
Debug: hiera(): Mysql Query returned 0 rows

**Comment by crayfishx** [comment] 2015-11-20 10:20
I think this may be somehow related to #15 - the behavior around the passing of key seems to be different in Hiera 3.x - I will do some more testing on this and fix/bug file where appropriate ...

**Comment by crayfishx** [comment] 2015-12-02 07:51
I think this is a duplicate of crayfishx/hiera-http#38 - Until confirmed otherwise, we will discuss the problem on that ticket....

**Closed** 2016-04-05 07:55 UTC
Labels: bug
